<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                "product_title" => "Banarasi Saree",
                "product_slug" => "banarasi-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => "Shah Industrial Pvt. Ltd.",
                "manufacturer_brand" => "Banarasi",
                "stocks" => 60,
                "product_price" => 5200.00,
                "compare_price" => 6000.00,
                "product_discount" => 20.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "16,14,12,10,3,6,8",
                "brands" => 6,
                "barcodes" => "150362",
                "released_date" => "2026-01-17 14=>00=>00",
                "created_at" => "2026-01-17 14=>10=>25",
                "updated_at" => "2026-01-17 14=>10=>25"
            ],
            [
                "product_title" => "Bandhani Saree",
                "product_slug" => "bandhani-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 80,
                "product_price" => 5000.00,
                "compare_price" => 9000.00,
                "product_discount" => 10.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "15,10,11,9,3,1,6,8",
                "brands" => 1,
                "barcodes" => "852145",
                "released_date" => "2026-01-17 14=>20=>00",
                "created_at" => "2026-01-17 14=>22=>10",
                "updated_at" => "2026-01-17 14=>22=>10"
            ],
            [
                "product_title" => "Bhagalpuri Silk Saree",
                "product_slug" => "bhagalpuri-silk-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 40,
                "product_price" => 4999.00,
                "compare_price" => 5000.00,
                "product_discount" => 30.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "2,10,11,15,9,1,13,12",
                "brands" => 6,
                "barcodes" => "851236",
                "released_date" => "2026-01-17 14=>22=>00",
                "created_at" => "2026-01-17 14=>23=>35",
                "updated_at" => "2026-01-17 14=>23=>35"
            ],
            [
                "product_title" => "Bomkai Saree",
                "product_slug" => "bomkai-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 60,
                "product_price" => 8999.00,
                "compare_price" => 10000.00,
                "product_discount" => null,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "13,10,7,1,15,11,13,10",
                "brands" => 3,
                "barcodes" => "742569",
                "released_date" => "2026-01-17 14=>23=>00",
                "created_at" => "2026-01-17 14=>24=>27",
                "updated_at" => "2026-01-17 14=>24=>57"
            ],
            [
                "product_title" => "Chanderi Saree",
                "product_slug" => "chanderi-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 60,
                "product_price" => 3999.00,
                "compare_price" => 5999.00,
                "product_discount" => 10.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "14,10,8,6,1,3,15,13",
                "brands" => 2,
                "barcodes" => "987452",
                "released_date" => "2026-01-17 14=>25=>00",
                "created_at" => "2026-01-17 14=>25=>59",
                "updated_at" => "2026-01-17 14=>25=>59"
            ],
            [
                "product_title" => "Chikankari Saree",
                "product_slug" => "chikankari-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 90,
                "product_price" => 7999.00,
                "compare_price" => 9999.00,
                "product_discount" => 10.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "16,11,13,15,1,3,9,10",
                "brands" => 5,
                "barcodes" => "741263",
                "released_date" => "2026-01-17 14=>25=>00",
                "created_at" => "2026-01-17 14=>26=>49",
                "updated_at" => "2026-01-17 14=>26=>49"
            ],
            [
                "product_title" => "Kanjivaram Silk Saree",
                "product_slug" => "kanjivaram-silk-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 70,
                "product_price" => 9999.00,
                "compare_price" => 12999.00,
                "product_discount" => 20.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "10,9,3,5,9,1,2,16,14",
                "brands" => 6,
                "barcodes" => "254793",
                "released_date" => "2026-01-17 14=>26=>00",
                "created_at" => "2026-01-17 14=>27=>37",
                "updated_at" => "2026-01-17 14=>27=>37"
            ],
            [
                "product_title" => "Kasavu Saree",
                "product_slug" => "kasavu-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 54,
                "product_price" => 7999.00,
                "compare_price" => 9999.00,
                "product_discount" => 20.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "7,9,15,11,3,4,1,2",
                "brands" => 5,
                "barcodes" => "965478",
                "released_date" => "2026-01-17 14=>27=>00",
                "created_at" => "2026-01-17 14=>28=>30",
                "updated_at" => "2026-01-17 14=>28=>30"
            ],
            [
                "product_title" => "Kosa Silk Saree",
                "product_slug" => "kosa-silk-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 64,
                "product_price" => 5699.00,
                "compare_price" => 8999.00,
                "product_discount" => 10.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "1,2,5,8,10,16,15",
                "brands" => 2,
                "barcodes" => "785214",
                "released_date" => "2026-01-17 14=>28=>00",
                "created_at" => "2026-01-17 14=>29=>15",
                "updated_at" => "2026-01-17 14=>29=>15"
            ],
            [
                "product_title" => "Madhubani Saree",
                "product_slug" => "madhubani-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 69,
                "product_price" => 7999.00,
                "compare_price" => 8999.00,
                "product_discount" => 20.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "15,16,8,3,4,13,12",
                "brands" => 1,
                "barcodes" => "852124",
                "released_date" => "2026-01-17 14=>29=>00",
                "created_at" => "2026-01-17 14=>30=>09",
                "updated_at" => "2026-01-17 14=>30=>09"
            ],
            [
                "product_title" => "Mangalagiri Cotton Silk Saree",
                "product_slug" => "mangalagiri-cotton-silk-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 96,
                "product_price" => 6999.00,
                "compare_price" => 7899.00,
                "product_discount" => 20.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "5,3,1,10,16,13,7,8",
                "brands" => 4,
                "barcodes" => "654741",
                "released_date" => "2026-01-17 14=>30=>00",
                "created_at" => "2026-01-17 14=>31=>00",
                "updated_at" => "2026-01-17 14=>31=>00"
            ],
            [
                "product_title" => "Muga Saree",
                "product_slug" => "muga-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 56,
                "product_price" => 9999.00,
                "compare_price" => 12999.00,
                "product_discount" => 20.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "10,16,14,13,2,1,5",
                "brands" => 6,
                "barcodes" => "547123",
                "released_date" => "2026-01-17 14=>31=>00",
                "created_at" => "2026-01-17 14=>31=>47",
                "updated_at" => "2026-01-17 14=>31=>47"
            ],
            [
                "product_title" => "Nauvari Saree",
                "product_slug" => "nauvari-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 69,
                "product_price" => 12999.00,
                "compare_price" => 15999.00,
                "product_discount" => 20.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "1,2,3,4,5,6,7,8",
                "brands" => 5,
                "barcodes" => "652111",
                "released_date" => "2026-01-17 14=>31=>00",
                "created_at" => "2026-01-17 14=>32=>40",
                "updated_at" => "2026-01-17 14=>32=>40"
            ],
            [
                "product_title" => "Patan Patola Saree",
                "product_slug" => "patan-patola-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 63,
                "product_price" => 13999.00,
                "compare_price" => 16999.00,
                "product_discount" => 20.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "3,1,6,15,10,11,5,9",
                "brands" => 3,
                "barcodes" => "874587",
                "released_date" => "2026-01-17 14=>32=>00",
                "created_at" => "2026-01-17 14=>33=>26",
                "updated_at" => "2026-01-18 20=>43=>19"
            ],
            [
                "product_title" => "Pochampally Saree",
                "product_slug" => "pochampally-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 32,
                "product_price" => 6999.00,
                "compare_price" => 8999.00,
                "product_discount" => 10.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "11,4,8,9,6,2,12,16",
                "brands" => 2,
                "barcodes" => "965236",
                "released_date" => "2026-01-17 14=>33=>00",
                "created_at" => "2026-01-17 14=>34=>17",
                "updated_at" => "2026-01-18 20=>42=>36"
            ],
            [
                "product_title" => "Tant Saree",
                "product_slug" => "tant-saree",
                "description" => "<p><strong>Details Description</strong></p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><strong>Sample Unordered List</strong></p><ul><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ul><p><strong>Sample Ordered Lista</strong></p><ol><li>Comodous in tempor ullamcorper miaculis</li><li>Pellentesque vitae neque mollis urna mattis laoreet.</li><li>Divamus sit amet purus justo.</li><li>Proin molestie egestas orci ac suscipit risus posuere loremous</li></ol>",
                "manufacturer_name" => null,
                "manufacturer_brand" => null,
                "stocks" => 58,
                "product_price" => 12999.00,
                "compare_price" => 15999.00,
                "product_discount" => 20.00,
                "is_featured" => "yes",
                "product_status" => "active",
                "meta_title" => null,
                "meta_keywords" => null,
                "meta_description" => null,
                "category" => 3,
                "child_category" => 6,
                "sub_category" => 36,
                "related_product" => "10,11,8,6,4,14,13",
                "brands" => 1,
                "barcodes" => "654456",
                "released_date" => "2026-01-17 14=>34=>00",
                "created_at" => "2026-01-17 14=>35=>07",
                "updated_at" => "2026-01-18 20=>42=>07"
            ]
        ];
        Product::insert($products);
    }
}
