<?php

namespace Database\Seeders;

use App\Models\SubCategory;
use Illuminate\Database\Seeder;

class SubCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sub_categoryries = [
            ['sub_category' => 'Premium Smartphones', 'slug' => 'premium-smartphones', 'child_category_id' => 1, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Best Laptops', 'slug' => 'best-laptops', 'child_category_id' => 1, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Top Headphones', 'slug' => 'top-headphones', 'child_category_id' => 1, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Highest Rated TVs', 'slug' => 'highest-rated-tvs', 'child_category_id' => 1, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Premium Watches', 'slug' => 'premium-watches', 'child_category_id' => 1, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Best Cameras', 'slug' => 'best-cameras', 'child_category_id' => 1, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Top Kitchen Appliances', 'slug' => 'top-kitchen-appliances', 'child_category_id' => 1, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Best Selling Mobiles', 'slug' => 'best-selling-mobiles', 'child_category_id' => 2, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Popular Headphones', 'slug' => 'popular-headphones', 'child_category_id' => 2, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Top Selling Laptops', 'slug' => 'top-selling-laptops', 'child_category_id' => 2, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'High Demand Smartwatches', 'slug' => 'high-demand-smartwatches', 'child_category_id' => 2, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Bestselling TVs', 'slug' => 'bestselling-tvs', 'child_category_id' => 2, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Popular Tablets', 'slug' => 'popular-tablets', 'child_category_id' => 2, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Most Bought Home Appliances', 'slug' => 'most-bought-home-appliances', 'child_category_id' => 2, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Viral Smartphones', 'slug' => 'viral-smartphones', 'child_category_id' => 3, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Trending Laptops', 'slug' => 'trending-laptops', 'child_category_id' => 3, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Popular Wearables', 'slug' => 'popular-wearables', 'child_category_id' => 3, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hot Gaming Gear', 'slug' => 'hot-gaming-gear', 'child_category_id' => 3, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Trending Audio Devices', 'slug' => 'trending-audio-devices', 'child_category_id' => 3, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Popular Camera Gear', 'slug' => 'popular-camera-gear', 'child_category_id' => 3, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Trending Smart Home', 'slug' => 'trending-smart-home', 'child_category_id' => 3, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Favorite Mobiles', 'slug' => 'favorite-mobiles', 'child_category_id' => 4, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Beloved Laptops', 'slug' => 'beloved-laptops', 'child_category_id' => 4, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Preferred Headphones', 'slug' => 'preferred-headphones', 'child_category_id' => 4, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Favorite Tablets', 'slug' => 'favorite-tablets', 'child_category_id' => 4, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Loved Smartwatches', 'slug' => 'loved-smartwatches', 'child_category_id' => 4, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Favorite Speakers', 'slug' => 'favorite-speakers', 'child_category_id' => 4, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Preferred Home Appliances', 'slug' => 'preferred-home-appliances', 'child_category_id' => 4, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Kids Clothing', 'slug' => 'kids-clothing', 'child_category_id' => 5, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Kids Footwear', 'slug' => 'kids-footwear', 'child_category_id' => 5, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Kids Toys', 'slug' => 'kids-toys', 'child_category_id' => 5, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Baby Care', 'slug' => 'baby-care', 'child_category_id' => 5, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'School Supplies', 'slug' => 'school-supplies', 'child_category_id' => 5, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Kids Accessories', 'slug' => 'kids-accessories', 'child_category_id' => 5, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Nursery Furniture', 'slug' => 'nursery-furniture', 'child_category_id' => 5, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Sarees', 'slug' => 'sarees', 'child_category_id' => 6, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Ethnic Wear', 'slug' => 'ethnic-wear', 'child_category_id' => 6, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Western Wear', 'slug' => 'western-wear', 'child_category_id' => 6, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Footwear', 'slug' => 'footwear', 'child_category_id' => 6, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Handbags', 'slug' => 'handbags', 'child_category_id' => 6, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Jewelry', 'slug' => 'jewelry', 'child_category_id' => 6, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Beauty Products', 'slug' => 'beauty-products', 'child_category_id' => 6, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Sofas', 'slug' => 'sofas', 'child_category_id' => 7, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'TV Units', 'slug' => 'tv-units', 'child_category_id' => 7, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Coffee Tables', 'slug' => 'coffee-tables', 'child_category_id' => 7, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Bookshelves', 'slug' => 'bookshelves', 'child_category_id' => 7, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Cabinets', 'slug' => 'cabinets', 'child_category_id' => 7, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Chairs & Ottomans', 'slug' => 'chairs-Ottomans', 'child_category_id' => 7, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Chairs', 'slug' => 'chairs', 'child_category_id' => 7, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Latest Mobiles', 'slug' => 'latest-mobiles', 'child_category_id' => 8, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'New Laptops', 'slug' => 'new-laptops', 'child_category_id' => 8, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Fresh Tablets', 'slug' => 'fresh-tablets', 'child_category_id' => 8, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'New Headphones', 'slug' => 'new-headphones', 'child_category_id' => 8, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Latest Smartwatches', 'slug' => 'latest-smartwatches', 'child_category_id' => 8, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'New Cameras', 'slug' => 'new-cameras', 'child_category_id' => 8, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Fresh Gaming Consoles', 'slug' => 'fresh-gaming-consoles', 'child_category_id' => 8, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Brand New Mobiles', 'slug' => 'brand-new-mobiles', 'child_category_id' => 9, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Recently Launched Laptops', 'slug' => 'recently-launched-laptops', 'child_category_id' => 9, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'New Audio Devices', 'slug' => 'new-audio-devices', 'child_category_id' => 9, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Fresh Wearables', 'slug' => 'fresh-wearables', 'child_category_id' => 9, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'New TV Models', 'slug' => 'new-tv-models', 'child_category_id' => 9, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Latest Tablets', 'slug' => 'latest-tablets', 'child_category_id' => 9, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Brand New Home Appliances', 'slug' => 'brand-new-home-appliances', 'child_category_id' => 9, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Hot Mobiles', 'slug' => 'hot-mobiles', 'child_category_id' => 10, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Popular Laptops', 'slug' => 'popular-laptops', 'child_category_id' => 10, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Trending Headphones', 'slug' => 'trending-headphones', 'child_category_id' => 10, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Viral Smartwatches', 'slug' => 'viral-smartwatches', 'child_category_id' => 10, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Popular TVs', 'slug' => 'popular-tvs', 'child_category_id' => 10, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Trending Tablets', 'slug' => 'trending-tablets', 'child_category_id' => 10, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hot Gaming Laptops', 'slug' => 'hot-gaming-laptops', 'child_category_id' => 10, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Newly Added Mobiles', 'slug' => 'newly-added-mobiles', 'child_category_id' => 11, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Recent Laptops', 'slug' => 'recent-laptops', 'child_category_id' => 11, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Fresh Headphones', 'slug' => 'fresh-headphones', 'child_category_id' => 11, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Newly Added Smartwatches', 'slug' => 'newly-added-smartwatches', 'child_category_id' => 11, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Recent TVs', 'slug' => 'recent-tvs', 'child_category_id' => 11, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Newly Added Tablets', 'slug' => 'newly-added-tablets', 'child_category_id' => 11, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Fresh Speakers', 'slug' => 'fresh-speakers', 'child_category_id' => 11, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Top Mobiles', 'slug' => 'top-mobiles', 'child_category_id' => 12, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Laptops', 'slug' => 'editor-laptops', 'child_category_id' => 12, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Recommended Headphones', 'slug' => 'recommended-headphones', 'child_category_id' => 12, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Selected Smartwatches', 'slug' => 'selected-smartwatches', 'child_category_id' => 12, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Top TVs', 'slug' => 'top-tvs', 'child_category_id' => 12, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Choice Tablets', 'slug' => 'choice-tablets', 'child_category_id' => 12, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Premium Audio', 'slug' => 'premium-audio', 'child_category_id' => 12, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Weekly Top Mobiles', 'slug' => 'weekly-top-mobiles', 'child_category_id' => 13, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hot Laptops', 'slug' => 'hot-laptops', 'child_category_id' => 13, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Weekly Headphones', 'slug' => 'weekly-headphones', 'child_category_id' => 13, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Trending Smartwatches', 'slug' => 'weekly-trending-smartwatches', 'child_category_id' => 13, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hot TVs', 'slug' => 'hot-tvs', 'child_category_id' => 13, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Weekly Tablets', 'slug' => 'weekly-tablets', 'child_category_id' => 13, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hot Gaming Consoles', 'slug' => 'hot-gaming-consoles', 'child_category_id' => 13, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Sofas & Couches', 'slug' => 'sofas-couches', 'child_category_id' => 14, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Entertainment Units', 'slug' => 'entertainment-units', 'child_category_id' => 14, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Center Tables', 'slug' => 'center-tables', 'child_category_id' => 14, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Wall Shelves', 'slug' => 'wall-shelves', 'child_category_id' => 14, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Cabinets & Storage', 'slug' => 'cabinets-storage', 'child_category_id' => 14, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Chairs & Recliners', 'slug' => 'chairs-recliners', 'child_category_id' => 14, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Decorative Lighting', 'slug' => 'decorative-lighting', 'child_category_id' => 14, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Dresses', 'slug' => 'dresses', 'child_category_id' => 15, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Tops & T-Shirts', 'slug' => 'tops-t-shirts', 'child_category_id' => 15, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Jeans & Pants', 'slug' => 'jeans-pants', 'child_category_id' => 15, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Skirts & Shorts', 'slug' => 'skirts-shorts', 'child_category_id' => 15, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Winter Wear', 'slug' => 'winter-wear', 'child_category_id' => 15, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Accessories', 'slug' => 'women-accessories', 'child_category_id' => 15, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Sleep & Lounge', 'slug' => 'sleep-lounge', 'child_category_id' => 15, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Casual Wear', 'slug' => 'casual-wear', 'child_category_id' => 16, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Formal Wear', 'slug' => 'formal-wear', 'child_category_id' => 16, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Party Wear', 'slug' => 'party-wear', 'child_category_id' => 16, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Denim Collection', 'slug' => 'denim-collection', 'child_category_id' => 16, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Shirts & Tops', 'slug' => 'shirts-tops', 'child_category_id' => 16, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Jackets & Coats', 'slug' => 'jackets-coats', 'child_category_id' => 16, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Active Wear', 'slug' => 'active-wear', 'child_category_id' => 16, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Sports Shoes', 'slug' => 'sports-shoes', 'child_category_id' => 17, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Casual Shoes', 'slug' => 'casual-shoes', 'child_category_id' => 17, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Formal Shoes', 'slug' => 'formal-shoes', 'child_category_id' => 17, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Sneakers', 'slug' => 'sneakers', 'child_category_id' => 17, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Sandals & Flip Flops', 'slug' => 'sandals-flip-flops', 'child_category_id' => 17, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Boots', 'slug' => 'boots', 'child_category_id' => 17, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Slippers', 'slug' => 'slippers', 'child_category_id' => 17, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Televisions', 'slug' => 'televisions', 'child_category_id' => 18, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Refrigerators', 'slug' => 'refrigerators', 'child_category_id' => 18, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Washing Machines', 'slug' => 'washing-machines', 'child_category_id' => 18, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Air Conditioners', 'slug' => 'air-conditioners', 'child_category_id' => 18, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Kitchen Appliances', 'slug' => 'kitchen-appliances', 'child_category_id' => 18, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Audio Systems', 'slug' => 'audio-systems', 'child_category_id' => 18, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Cameras', 'slug' => 'cameras', 'child_category_id' => 18, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Smartphones', 'slug' => 'smartphones', 'child_category_id' => 19, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Mobile Cases', 'slug' => 'mobile-cases', 'child_category_id' => 19, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Screen Protectors', 'slug' => 'screen-protectors', 'child_category_id' => 19, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Power Banks', 'slug' => 'power-banks', 'child_category_id' => 19, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Chargers', 'slug' => 'chargers', 'child_category_id' => 19, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Headphones & Earphones', 'slug' => 'headphones-earphones', 'child_category_id' => 19, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Selfie Sticks', 'slug' => 'selfie-sticks', 'child_category_id' => 19, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Face Wash & Cleansers', 'slug' => 'face-wash-cleansers', 'child_category_id' => 20, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Moisturizers', 'slug' => 'moisturizers', 'child_category_id' => 20, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Serums & Essences', 'slug' => 'serums-essences', 'child_category_id' => 20, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Sunscreens', 'slug' => 'sunscreens', 'child_category_id' => 20, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Face Masks', 'slug' => 'face-masks', 'child_category_id' => 20, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Toners', 'slug' => 'toners', 'child_category_id' => 20, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Anti-Aging Products', 'slug' => 'anti-aging-products', 'child_category_id' => 20, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Shampoos', 'slug' => 'shampoos', 'child_category_id' => 21, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Conditioners', 'slug' => 'conditioners', 'child_category_id' => 21, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hair Oils', 'slug' => 'hair-oils', 'child_category_id' => 21, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hair Serums', 'slug' => 'hair-serums', 'child_category_id' => 21, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hair Masks', 'slug' => 'hair-masks', 'child_category_id' => 21, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hair Color', 'slug' => 'hair-color', 'child_category_id' => 21, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Styling Products', 'slug' => 'styling-products', 'child_category_id' => 21, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Shaving Products', 'slug' => 'shaving-products', 'child_category_id' => 22, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Face Care', 'slug' => 'face-care', 'child_category_id' => 22, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hair Care', 'slug' => 'men-hair-care', 'child_category_id' => 22, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Body Care', 'slug' => 'body-care', 'child_category_id' => 22, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Fragrances', 'slug' => 'fragrances', 'child_category_id' => 22, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Beard Care', 'slug' => 'beard-care', 'child_category_id' => 22, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Personal Hygiene', 'slug' => 'personal-hygiene', 'child_category_id' => 22, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Eye Liner', 'slug' => 'eye-liner', 'child_category_id' => 23, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Skin Care', 'slug' => 'skin-care', 'child_category_id' => 23, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Lipstick', 'slug' => 'lipstick', 'child_category_id' => 23, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Makeup & Cosmetics', 'slug' => 'makeup-cosmetics', 'child_category_id' => 23, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Fragrances & Perfumes', 'slug' => 'fragrances-perfumes', 'child_category_id' => 23, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Bath & Body', 'slug' => 'bath-body', 'child_category_id' => 23, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Men\'s Grooming', 'slug' => 'mens-grooming', 'child_category_id' => 23, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Touch Phones', 'slug' => 'touch-phones', 'child_category_id' => 24, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Feature Phones', 'slug' => 'feature-phones', 'child_category_id' => 24, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gaming Phones', 'slug' => 'gaming-phones', 'child_category_id' => 24, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Budget Phones', 'slug' => 'budget-phones', 'child_category_id' => 24, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Foldable Phones', 'slug' => 'foldable-phones', 'child_category_id' => 24, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Camera Phones', 'slug' => 'camera-phones', 'child_category_id' => 24, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Business Phones', 'slug' => 'business-phones', 'child_category_id' => 24, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Gaming Laptops', 'slug' => 'gaming-laptops', 'child_category_id' => 25, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Ultrabooks', 'slug' => 'ultrabooks', 'child_category_id' => 25, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Business Laptops', 'slug' => 'business-laptops', 'child_category_id' => 25, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Student Laptops', 'slug' => 'student-laptops', 'child_category_id' => 25, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => '2-in-1 Laptops', 'slug' => '2-in-1-laptops', 'child_category_id' => 25, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Budget Laptops', 'slug' => 'budget-laptops', 'child_category_id' => 25, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Workstation Laptops', 'slug' => 'workstation-laptops', 'child_category_id' => 25, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Smart Watches', 'slug' => 'smart-watches', 'child_category_id' => 26, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Fitness Trackers', 'slug' => 'fitness-trackers', 'child_category_id' => 26, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Smart Speakers', 'slug' => 'smart-speakers', 'child_category_id' => 26, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Smart Cameras', 'slug' => 'smart-cameras', 'child_category_id' => 26, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'VR Headsets', 'slug' => 'vr-headsets', 'child_category_id' => 26, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Smart Home Devices', 'slug' => 'smart-home-devices', 'child_category_id' => 26, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Wearable Tech', 'slug' => 'wearable-tech', 'child_category_id' => 26, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Wireless Earbuds', 'slug' => 'wireless-earbuds', 'child_category_id' => 27, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Bluetooth Headphones', 'slug' => 'bluetooth-headphones', 'child_category_id' => 27, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gaming Headsets', 'slug' => 'gaming-headsets', 'child_category_id' => 27, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Noise Cancelling Headphones', 'slug' => 'noise-cancelling-headphones', 'child_category_id' => 27, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Sports Earphones', 'slug' => 'sports-earphones', 'child_category_id' => 27, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Studio Headphones', 'slug' => 'studio-headphones', 'child_category_id' => 27, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Neckband Earphones', 'slug' => 'neckband-earphones', 'child_category_id' => 27, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Teddy Bears', 'slug' => 'teddy-bears', 'child_category_id' => 28, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Plush Animals', 'slug' => 'plush-animals', 'child_category_id' => 28, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Character Toys', 'slug' => 'character-toys', 'child_category_id' => 28, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Pillow Pets', 'slug' => 'pillow-pets', 'child_category_id' => 28, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Giant Stuffed Toys', 'slug' => 'giant-stuffed-toys', 'child_category_id' => 28, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Interactive Plush', 'slug' => 'interactive-plush', 'child_category_id' => 28, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Limited Edition Stuffed', 'slug' => 'limited-edition-stuffed', 'child_category_id' => 28, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'STEM Kits', 'slug' => 'stem-kits', 'child_category_id' => 29, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Building Blocks', 'slug' => 'building-blocks', 'child_category_id' => 29, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Puzzle Games', 'slug' => 'puzzle-games', 'child_category_id' => 29, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Science Kits', 'slug' => 'science-kits', 'child_category_id' => 29, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Math Learning Toys', 'slug' => 'math-learning-toys', 'child_category_id' => 29, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Language Learning', 'slug' => 'language-learning', 'child_category_id' => 29, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Montessori Toys', 'slug' => 'montessori-toys', 'child_category_id' => 29, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Strategy Games', 'slug' => 'strategy-games', 'child_category_id' => 30, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Family Board Games', 'slug' => 'family-board-games', 'child_category_id' => 30, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Card Games', 'slug' => 'card-games', 'child_category_id' => 30, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Party Games', 'slug' => 'party-games', 'child_category_id' => 30, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Classic Board Games', 'slug' => 'classic-board-games', 'child_category_id' => 30, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Cooperative Games', 'slug' => 'cooperative-games', 'child_category_id' => 30, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Trivia Games', 'slug' => 'trivia-games', 'child_category_id' => 30, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Birthday Decorations', 'slug' => 'birthday-decorations', 'child_category_id' => 31, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Personalized Gifts', 'slug' => 'personalized-gifts', 'child_category_id' => 31, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gift Sets', 'slug' => 'gift-sets', 'child_category_id' => 31, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Return Gifts', 'slug' => 'return-gifts', 'child_category_id' => 31, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Birthday Cards', 'slug' => 'birthday-cards', 'child_category_id' => 31, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Balloons & Confetti', 'slug' => 'balloons-confetti', 'child_category_id' => 31, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Cake Toppers', 'slug' => 'cake-toppers', 'child_category_id' => 31, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Phone Cases', 'slug' => 'phone-cases', 'child_category_id' => 32, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Glass Guard', 'slug' => 'glass-Guard', 'child_category_id' => 32, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Pendrives', 'slug' => 'pendrives', 'child_category_id' => 32, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Virtual Box', 'slug' => 'virtual-box', 'child_category_id' => 32, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Mobile Stands', 'slug' => 'mobile-stands', 'child_category_id' => 32, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Memory Cards', 'slug' => 'memory-cards', 'child_category_id' => 32, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'OTG Adapters', 'slug' => 'otg-adapters', 'child_category_id' => 32, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Gaming Consoles', 'slug' => 'gaming-consoles', 'child_category_id' => 33, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gaming Controllers', 'slug' => 'gaming-controllers', 'child_category_id' => 33, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gaming PC', 'slug' => 'gaming-pc', 'child_category_id' => 33, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gaming Keyboards', 'slug' => 'gaming-keyboards', 'child_category_id' => 33, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gaming Mice', 'slug' => 'gaming-mice', 'child_category_id' => 33, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gaming Chairs', 'slug' => 'gaming-chairs', 'child_category_id' => 33, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gaming Monitors', 'slug' => 'gaming-monitors', 'child_category_id' => 33, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Wireless Earphones', 'slug' => 'wireless-earphones', 'child_category_id' => 34, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Bluetooth Speakers', 'slug' => 'bluetooth-speakers', 'child_category_id' => 34, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Soundbars', 'slug' => 'soundbars', 'child_category_id' => 34, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Wired Headphones', 'slug' => 'wired-headphones', 'child_category_id' => 34, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Home Theater Systems', 'slug' => 'home-theater-systems', 'child_category_id' => 34, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Earbuds', 'slug' => 'earbuds', 'child_category_id' => 34, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Portable Speakers', 'slug' => 'portable-speakers', 'child_category_id' => 34, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Fast Chargers', 'slug' => 'fast-chargers', 'child_category_id' => 35, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'USB Cables', 'slug' => 'usb-cables', 'child_category_id' => 35, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Car Chargers', 'slug' => 'car-chargers', 'child_category_id' => 35, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Wireless Chargers', 'slug' => 'wireless-chargers', 'child_category_id' => 35, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Multi Port Chargers', 'slug' => 'multi-port-chargers', 'child_category_id' => 35, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Data Cables', 'slug' => 'data-cables', 'child_category_id' => 35, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Adapter Plugs', 'slug' => 'adapter-plugs', 'child_category_id' => 35, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'School Backpacks', 'slug' => 'school-backpacks', 'child_category_id' => 36, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Laptop Backpacks', 'slug' => 'laptop-backpacks', 'child_category_id' => 36, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Travel Backpacks', 'slug' => 'travel-backpacks', 'child_category_id' => 36, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Hiking Backpacks', 'slug' => 'hiking-backpacks', 'child_category_id' => 36, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Mini Backpacks', 'slug' => 'mini-backpacks', 'child_category_id' => 36, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Waterproof Backpacks', 'slug' => 'waterproof-backpacks', 'child_category_id' => 36, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Fashion Backpacks', 'slug' => 'fashion-backpacks', 'child_category_id' => 36, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Oxford Shoes', 'slug' => 'oxford-shoes', 'child_category_id' => 37, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Loafers', 'slug' => 'loafers', 'child_category_id' => 37, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Slip-ons', 'slug' => 'slip-ons', 'child_category_id' => 37, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Canvas Shoes', 'slug' => 'canvas-shoes', 'child_category_id' => 37, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Casual Boots', 'slug' => 'casual-boots', 'child_category_id' => 37, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Espadrilles', 'slug' => 'espadrilles', 'child_category_id' => 37, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Moccasins', 'slug' => 'moccasins', 'child_category_id' => 37, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Tote Bags', 'slug' => 'tote-bags', 'child_category_id' => 38, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Clutch Bags', 'slug' => 'clutch-bags', 'child_category_id' => 38, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Shoulder Bags', 'slug' => 'shoulder-bags', 'child_category_id' => 38, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Crossbody Bags', 'slug' => 'crossbody-bags', 'child_category_id' => 38, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Satchels', 'slug' => 'satchels', 'child_category_id' => 38, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Evening Bags', 'slug' => 'evening-bags', 'child_category_id' => 38, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Designer Handbags', 'slug' => 'designer-handbags', 'child_category_id' => 38, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Running Shoes', 'slug' => 'running-shoes', 'child_category_id' => 39, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Training Shoes', 'slug' => 'training-shoes', 'child_category_id' => 39, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Basketball Shoes', 'slug' => 'basketball-shoes', 'child_category_id' => 39, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Football Shoes', 'slug' => 'football-shoes', 'child_category_id' => 39, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Walking Shoes', 'slug' => 'walking-shoes', 'child_category_id' => 39, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Trekking Shoes', 'slug' => 'trekking-shoes', 'child_category_id' => 39, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Gym Shoes', 'slug' => 'gym-shoes', 'child_category_id' => 39, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Vitamins', 'slug' => 'vitamins', 'child_category_id' => 48, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Protein Supplements', 'slug' => 'protein-supplements', 'child_category_id' => 48, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Herbal Supplements', 'slug' => 'herbal-supplements', 'child_category_id' => 48, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Weight Management', 'slug' => 'weight-management', 'child_category_id' => 48, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Digestive Health', 'slug' => 'digestive-health', 'child_category_id' => 48, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Energy Boosters', 'slug' => 'energy-boosters', 'child_category_id' => 48, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Immune Support', 'slug' => 'immune-support', 'child_category_id' => 48, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Organic Skincare', 'slug' => 'organic-skincare', 'child_category_id' => 49, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Ayurvedic Products', 'slug' => 'ayurvedic-products', 'child_category_id' => 49, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Natural Hair Care', 'slug' => 'natural-hair-care', 'child_category_id' => 49, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Essential Oils', 'slug' => 'essential-oils', 'child_category_id' => 49, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Herbal Teas', 'slug' => 'herbal-teas', 'child_category_id' => 49, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Organic Makeup', 'slug' => 'organic-makeup', 'child_category_id' => 49, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Natural Body Care', 'slug' => 'natural-body-care', 'child_category_id' => 49, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Lipstick & Lip Gloss', 'slug' => 'lipstick-lip-gloss', 'child_category_id' => 50, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Foundation', 'slug' => 'foundation', 'child_category_id' => 50, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Eye Makeup', 'slug' => 'eye-makeup', 'child_category_id' => 50, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Makeup Brushes', 'slug' => 'makeup-brushes', 'child_category_id' => 50, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Blush & Bronzer', 'slug' => 'blush-bronzer', 'child_category_id' => 50, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Makeup Kits', 'slug' => 'makeup-kits', 'child_category_id' => 50, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Makeup Remover', 'slug' => 'makeup-remover', 'child_category_id' => 50, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Perfumes', 'slug' => 'perfumes', 'child_category_id' => 51, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Body Sprays', 'slug' => 'body-sprays', 'child_category_id' => 51, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Deodorants', 'slug' => 'deodorants', 'child_category_id' => 51, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Room Fragrances', 'slug' => 'room-fragrances', 'child_category_id' => 51, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Essential Oil Blends', 'slug' => 'essential-oil-blends', 'child_category_id' => 51, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Scented Candles', 'slug' => 'scented-candles', 'child_category_id' => 51, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Attars', 'slug' => 'attars', 'child_category_id' => 51, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'LED Bulbs', 'slug' => 'led-bulbs', 'child_category_id' => 52, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'LED Strips', 'slug' => 'led-strips', 'child_category_id' => 52, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'LED Panel Lights', 'slug' => 'led-panel-lights', 'child_category_id' => 52, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'LED Spotlights', 'slug' => 'led-spotlights', 'child_category_id' => 52, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'LED Tube Lights', 'slug' => 'led-tube-lights', 'child_category_id' => 52, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'LED Downlights', 'slug' => 'led-downlights', 'child_category_id' => 52, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'LED String Lights', 'slug' => 'led-string-lights', 'child_category_id' => 52, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Wall Art', 'slug' => 'wall-art', 'child_category_id' => 53, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Photo Frames', 'slug' => 'photo-frames', 'child_category_id' => 53, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Decorative Items', 'slug' => 'decorative-items', 'child_category_id' => 53, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Clocks', 'slug' => 'clocks', 'child_category_id' => 53, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Mirrors', 'slug' => 'mirrors', 'child_category_id' => 53, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Cushions & Pillows', 'slug' => 'cushions-pillows', 'child_category_id' => 53, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Vases', 'slug' => 'vases', 'child_category_id' => 53, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Smart Bulbs', 'slug' => 'smart-bulbs', 'child_category_id' => 54, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Smart Switches', 'slug' => 'smart-switches', 'child_category_id' => 54, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Smart LED Strips', 'slug' => 'smart-led-strips', 'child_category_id' => 54, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Motion Sensor Lights', 'slug' => 'motion-sensor-lights', 'child_category_id' => 54, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'WiFi Lights', 'slug' => 'wifi-lights', 'child_category_id' => 54, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Voice Controlled Lights', 'slug' => 'voice-controlled-lights', 'child_category_id' => 54, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Smart Lighting Kits', 'slug' => 'smart-lighting-kits', 'child_category_id' => 54, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],

            ['sub_category' => 'Cookware', 'slug' => 'cookware', 'child_category_id' => 55, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Dinner Sets', 'slug' => 'dinner-sets', 'child_category_id' => 55, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Kitchen Tools', 'slug' => 'kitchen-tools', 'child_category_id' => 55, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Storage Containers', 'slug' => 'storage-containers', 'child_category_id' => 55, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Cutlery', 'slug' => 'cutlery', 'child_category_id' => 55, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Glassware', 'slug' => 'glassware', 'child_category_id' => 55, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
            ['sub_category' => 'Table Linens', 'slug' => 'table-linens', 'child_category_id' => 55, 'status' => 'active', 'created_at' => now(), 'updated_at' => now()],
        ];

        SubCategory::insert($sub_categoryries);
    }
}
